-- Migration 015: generic page_content_items table
-- Makes the marketing/landing-page copy (About, Services, Realtor landing,
-- Property Management landing, and the two homepage sections that were still
-- 100% hardcoded) admin-editable from the DB, per Joan's "whole main website
-- in one push" instruction (Sep 2026).
--
-- Seed data below reproduces the exact current hardcoded copy, so running
-- this migration causes ZERO visible change to the site until an admin
-- actively edits something in Site Content > Page Content.

CREATE TABLE IF NOT EXISTS page_content_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  page VARCHAR(60) NOT NULL,
  section VARCHAR(80) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  icon VARCHAR(60) NULL,
  image_path VARCHAR(500) NULL,
  title VARCHAR(255) NULL,
  subtitle VARCHAR(255) NULL,
  description TEXT NULL,
  extra JSON NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_page_content_page (page),
  INDEX idx_page_content_page_section (page, section, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO page_content_items
  (page, section, sort_order, icon, image_path, title, subtitle, description, extra, is_active)
VALUES
  ('about', 'about-hero', 1, NULL, NULL, 'Dream Home Meets Trusted Expertise', NULL, 'At HouseBank, we pride ourselves on being more than just a real estate agency, we are your partners in finding the perfect space to live, work, and thrive.', '{"badge": "Welcome to HouseBank", "paragraph2": "Whether you''re searching for a family home, an investment property, or a commercial space, we are committed to helping you achieve your goals with professionalism and care", "cta_text": "Explore Properties", "cta_link": "/explore"}', 1),
  ('about', 'about-top-features', 1, NULL, NULL, 'Explore', 'Great Neighborhoods', 'We connect with directly to the person that knows the most about property for sale, the listing realtor.', '{"style": "white", "cta_text": "Explore", "cta_link": "/explore"}', 1),
  ('about', 'about-top-features', 2, NULL, NULL, 'Find Highly', 'Rated Best Property', 'We connect with directly to the person that knows the most about property for sale, the listing realtor.', '{"style": "purple", "cta_text": "Explore", "cta_link": "/explore"}', 1),
  ('about', 'about-top-features', 3, NULL, NULL, 'Discover', 'Quality Buildings', 'We connect with directly to the person that knows the most about property for sale, the listing realtor.', '{"style": "white", "cta_text": "Explore", "cta_link": "/explore"}', 1),
  ('about', 'about-who-we-are', 1, NULL, NULL, 'We are Best in Property Management Trusted by 10 Million Buyers', NULL, 'Founded on a passion for connecting people with the right properties, HouseBank Real Estate has grown to become a trusted name in the real estate industry. Our team of experienced realtors combines market insight with personalized service, ensuring you receive the guidance you need at every step of your property journey.', '{"eyebrow": "Who We Are"}', 1),
  ('about', 'about-why-choose-us', 0, NULL, NULL, 'Why Choose Us?', NULL, NULL, '{"kind": "header", "cta_text": "Explore Properties", "cta_link": "/explore"}', 1),
  ('about', 'about-why-choose-us', 1, NULL, NULL, 'Customer-Centric Approach:', NULL, 'Your satisfaction is our priority. We listen, understand, and deliver solutions tailored to your needs.', NULL, 1),
  ('about', 'about-why-choose-us', 2, NULL, NULL, 'Transparency and Integrity:', NULL, 'Honesty and fairness guide everything we do.', NULL, 1),
  ('about', 'about-why-choose-us', 3, NULL, NULL, 'Market Expertise:', NULL, 'With a deep understanding of the real estate market, we provide insights to help you make confident decisions.', NULL, 1),
  ('about', 'about-why-choose-us', 4, NULL, NULL, 'End-to-End Support:', NULL, 'From property search to closing the deal, we are with you every step of the way.', NULL, 1),
  ('about', 'about-bottom-features', 1, 'Star', NULL, 'Our Mission', NULL, 'To connect people with properties that inspire them and meet their needs while ensuring a seamless and rewarding process for all our clients.', '{"additionalText": "At HouseBank Real Estate, we don''t just sell properties—we help you build a foundation for your future. Let''s find your dream home today!"}', 1),
  ('about', 'about-bottom-features', 2, 'Star', NULL, 'Our Vision', NULL, 'To be the trusted leader in real estate, transforming lives by providing exceptional properties and services that inspire dreams, build communities, and create lasting value for generations to come.', NULL, 1),
  ('about', 'about-bottom-features', 3, 'Star', NULL, 'Our Aim', NULL, 'At HouseBank Real Estate, our goal is to make property ownership and investment seamless, trustworthy, and rewarding. We strive to connect individuals and businesses with the perfect spaces while fostering lasting relationships built on transparency, expertise, and care. Your dream property is our mission.', NULL, 1),
  ('about', 'about-team', 0, NULL, NULL, 'Our Team', NULL, 'At House Bank Real Estate, we make renting, buying, and investing in property seamless and rewarding. Whether you''re looking for your next home, rental space, or a lucrative investment opportunity, our team is here to guide you every step of the way.', '{"kind": "header"}', 1),
  ('about', 'about-team', 1, NULL, NULL, 'Oluwafemi Adegbanga', 'Founder & CEO', 'With a vision to revolutionize the real estate industry, Oluwafemi founded HouseBank Real Estate to offer personalized and innovative property solutions, leading the team with integrity, innovation, and a client-first approach.', '{"twitter": "#", "facebook": "#", "linkedin": "#"}', 1),
  ('about', 'about-team', 2, NULL, NULL, 'Oluwafemi Adegbanga', 'Chief Operating Officer', 'As Chief Operating Officer, Oluwafemi oversees day-to-day operations at HouseBank Real Estate, making sure every client interaction reflects our commitment to integrity, innovation, and a client-first approach.', '{"twitter": "#", "facebook": "#", "linkedin": "#"}', 1),
  ('about', 'about-team', 3, NULL, NULL, 'Oluwafemi Adegbanga', 'Senior Sales Manager', 'As Senior Sales Manager, Oluwafemi leads the sales team at HouseBank Real Estate, helping clients navigate the market with expert guidance built on integrity, innovation, and a client-first approach.', '{"twitter": "#", "facebook": "#", "linkedin": "#"}', 1),
  ('about', 'about-team', 4, NULL, NULL, 'Oluwafemi Adegbanga', 'Leasing Consultant', 'As a Leasing Consultant at HouseBank Real Estate, Oluwafemi helps tenants and property owners find the right fit, guided by integrity, innovation, and a client-first approach.', '{"twitter": "#", "facebook": "#", "linkedin": "#"}', 1),
  ('services', 'services-hero', 1, NULL, NULL, 'Your Trusted Partner in Real Estate', NULL, 'At House Bank Real Estate, we are committed to providing you with exceptional real estate solutions tailored to meet your unique needs. Whether you''re buying your dream home, selling a property, or investing in real estate, we''ve got you covered.', '{"badge": "our Service", "cta_text": "Explore our Offer", "stats": [{"number": "20k", "label": "Happy customers"}, {"number": "10k +", "label": "Client reviews"}, {"number": "4.5", "label": "Positive Rating"}]}', 1),
  ('services', 'services-detail', 0, NULL, NULL, 'What We Do For You', NULL, NULL, '{"kind": "header", "eyebrow": "Services we Provide"}', 1),
  ('services', 'services-detail', 1, NULL, 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1926&q=80', 'Property Management', NULL, 'We handle every aspect of managing your property so you can enjoy the benefits without the stress.', '{"layout": "image-left", "bullets": ["Tenant screening, placement, and support.", "Rent collection and income disbursement.", "Maintenance, repairs, and regular property inspections.", "Legal compliance and documentation."], "what_you_get": "Peace of mind knowing your property is in expert hands while maximizing returns."}', 1),
  ('services', 'services-detail', 2, NULL, 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2026&q=80', 'Property Valuation', NULL, 'Understand the true value of your property with our accurate and reliable valuation services.', '{"layout": "content-left", "bullets": ["Market analysis and data-driven insights.", "Expert assessment of residential, commercial, and land properties.", "Comprehensive reports for sales, purchases, or investment decisions."], "what_you_get": "Confidence in making informed real estate decisions backed by expert evaluations."}', 1),
  ('services', 'services-detail', 3, NULL, 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Property Exchange', NULL, 'Looking to upgrade, downsize, or diversify your portfolio? Our property exchange service makes transitions easy.', '{"layout": "image-left", "bullets": ["Seamless swapping of properties to suit your evolving needs.", "Wide network of listings for residential, commercial, and investment properties.", "Transparent and efficient processes to match you with the perfect exchange."], "what_you_get": "Flexibility to adapt your property portfolio without the hassle of traditional sales."}', 1),
  ('services', 'services-detail', 4, NULL, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80', 'Investment Portfolio', NULL, 'Grow your wealth with tailored real estate investment strategies.', '{"layout": "content-left", "bullets": ["Portfolio analysis and optimization.", "Access to high-yield investment opportunities.", "Expert guidance on market trends and forecasts.", "Strategic advice for diversifying and maximizing returns."], "what_you_get": "A lucrative and secure investment portfolio aligned with your financial goals."}', 1),
  ('services', 'services-why-choose-us', 0, NULL, NULL, 'Why Choose Us?', NULL, NULL, '{"kind": "header", "eyebrow": "Services we Provide"}', 1),
  ('services', 'services-why-choose-us', 1, NULL, NULL, 'Expertise You Can Trust', NULL, 'Years of experience in real estate and investment.', '{"style": "white"}', 1),
  ('services', 'services-why-choose-us', 2, NULL, NULL, 'Client-Centric Approach', NULL, 'Tailored services to meet your unique needs.', '{"style": "purple"}', 1),
  ('services', 'services-why-choose-us', 3, NULL, NULL, 'Transparency and Integrity', NULL, 'Clear communication and ethical practices.', '{"style": "white"}', 1),
  ('services', 'services-why-choose-us', 4, NULL, NULL, 'Client-Centric Approach', NULL, 'Tailored services to meet your unique needs.', '{"style": "purple"}', 1),
  ('realtor', 'realtor-hero', 1, NULL, NULL, 'Become an Realtor', NULL, 'Effortlessly buy, sell, and invest in real estate with HouseBank. Whether you''re a realtor, developer, or investor, we provide the tools and connections you need to close deals faster and grow your business.', '{"cta_text": "Register Now", "stats": [{"icon": "Users", "number": "20,000+", "label": "Registered Realtors"}, {"icon": "Home", "number": "50k+", "label": "Houses Uploaded"}, {"icon": "₦", "number": "₦15M", "label": "Amount Realtors Paid"}]}', 1),
  ('realtor', 'realtor-partners', 0, NULL, NULL, 'Our Partners', NULL, NULL, '{"kind": "header"}', 1),
  ('realtor', 'realtor-partners', 1, NULL, NULL, 'Check D''Deck Homes', NULL, NULL, NULL, 1),
  ('realtor', 'realtor-partners', 2, NULL, NULL, 'Lane*Wey', NULL, NULL, NULL, 1),
  ('realtor', 'realtor-partners', 3, NULL, NULL, 'Telos Properties', NULL, NULL, NULL, 1),
  ('realtor', 'realtor-partners', 4, NULL, NULL, 'Golden Partner', NULL, NULL, NULL, 1),
  ('realtor', 'realtor-why-join-steps', 0, NULL, NULL, 'HouseBank', NULL, NULL, '{"kind": "header", "eyebrow": "Why Join Us"}', 1),
  ('realtor', 'realtor-why-join-steps', 1, NULL, NULL, 'Easy sign up', NULL, 'Start with a free consultation to assess your needs. You''ll provide information about your home and what you would like to get out of your battery storage. You''ll work with an experienced design consultant to evaluate the best solution for you.', NULL, 1),
  ('realtor', 'realtor-why-join-steps', 2, NULL, NULL, 'Connect with customers easily', NULL, 'Our platform makes it simple to connect with potential customers in your area. Get matched with qualified leads and build lasting relationships.', NULL, 1),
  ('realtor', 'realtor-why-join-steps', 3, NULL, NULL, 'Maximum your growth with Housebank', NULL, 'Leverage our tools and resources to expand your business. Access market insights, professional development, and growth opportunities.', NULL, 1),
  ('realtor', 'realtor-why-join-steps', 4, NULL, NULL, 'Withdraw your Earnings fast', NULL, 'Get paid quickly and securely. Our streamlined payment system ensures you receive your earnings without delay.', NULL, 1),
  ('realtor', 'realtor-features', 0, NULL, NULL, 'What Makes HouseBank Stand Out', NULL, 'Effortlessly buy, sell, and invest in real estate with HouseBank. Whether you''re a realtor, developer, or investor, we provide the tools and connections you need to close deals faster and grow your business.', '{"kind": "header", "eyebrow": "Our Features", "bottom_cta_title": "Ready to take your real estate business to the next level", "bottom_cta_text": "Start listing"}', 1),
  ('realtor', 'realtor-features', 1, NULL, NULL, 'Seamless Property Listings', NULL, 'Easily upload, manage, and showcase your properties to a wide audience with our intuitive listing platform.', NULL, 1),
  ('realtor', 'realtor-features', 2, NULL, NULL, 'Verified Leads & High-Quality Buyers', NULL, 'Connect with serious buyers and investors, ensuring faster and more secure transactions.', NULL, 1),
  ('realtor', 'realtor-features', 3, NULL, NULL, 'Secure & Transparent Transactions', NULL, 'Conduct business with confidence using our secure payment and verification system.', NULL, 1),
  ('realtor', 'realtor-features', 4, NULL, NULL, 'Dedicated Support & Marketing Tools', NULL, 'Get expert assistance, promotional tools, and marketing strategies to boost your property sales.', NULL, 1),
  ('realtor', 'realtor-features', 5, NULL, NULL, 'AI-Powered Matching', NULL, 'Our smart recommendation system connects you with the right buyers and properties based on preferences and market demand.', NULL, 1),
  ('realtor', 'realtor-features', 6, NULL, NULL, 'Real-Time Market Insights', NULL, 'Stay ahead with in-depth property analytics and trends to make informed decisions.', NULL, 1),
  ('realtor', 'realtor-benefits', 0, NULL, NULL, 'Benefits for Realtor & Developers', 'Grow Your Real Estate Business with HouseBank', NULL, '{"kind": "header", "title_highlight": "Realtor &", "bottom_cta_title": "Join HouseBank today and take your real estate career to new heights!", "bottom_cta_text": "Start listing"}', 1),
  ('realtor', 'realtor-benefits', 1, NULL, NULL, 'Maximize Your Sales', NULL, 'Reach a targeted audience and attract more buyers.', '{"group": "developer"}', 1),
  ('realtor', 'realtor-benefits', 2, NULL, NULL, 'Data-Driven Marketing', NULL, 'Use real-time insights to improve your sales strategy.', '{"group": "developer"}', 1),
  ('realtor', 'realtor-benefits', 3, NULL, NULL, 'High-Quality Exposure', NULL, 'Showcase your projects with stunning visuals and virtual tours.', '{"group": "developer"}', 1),
  ('realtor', 'realtor-benefits', 4, NULL, NULL, 'Direct Investor Connections', NULL, 'Connect with serious investors ready to fund your projects.', '{"group": "developer"}', 1),
  ('realtor', 'realtor-benefits', 5, NULL, NULL, 'End-to-End Support', NULL, 'From listing to closing, we streamline the entire process.', '{"group": "developer"}', 1),
  ('realtor', 'realtor-benefits', 6, NULL, NULL, 'Expand Your Reach', NULL, 'Get your listings in front of serious buyers and investors.', '{"group": "realtor"}', 1),
  ('realtor', 'realtor-benefits', 7, NULL, NULL, 'Lead Management', NULL, 'Access verified leads and manage inquiries with ease.', '{"group": "realtor"}', 1),
  ('realtor', 'realtor-benefits', 8, NULL, NULL, 'Fast & Secure Transactions', NULL, 'Close deals efficiently with our secure platform.', '{"group": "realtor"}', 1),
  ('realtor', 'realtor-benefits', 9, NULL, NULL, 'AI-Powered Property Matching', NULL, 'Get matched with buyers looking for properties like yours.', '{"group": "realtor"}', 1),
  ('realtor', 'realtor-benefits', 10, NULL, NULL, 'Professional Branding', NULL, 'Enhance your credibility with a customized realtor profile.', '{"group": "realtor"}', 1),
  ('realtor', 'realtor-why-choose-us', 0, NULL, NULL, 'Why Choose Us?', NULL, NULL, '{"kind": "header", "cta_text": "Sign up"}', 1),
  ('realtor', 'realtor-why-choose-us', 1, NULL, NULL, 'Customer-Centric Approach:', NULL, 'Your satisfaction is our priority. We listen, understand, and deliver solutions tailored to your needs.', NULL, 1),
  ('realtor', 'realtor-why-choose-us', 2, NULL, NULL, 'Transparency and Integrity:', NULL, 'Honesty and fairness guide everything we do.', NULL, 1),
  ('realtor', 'realtor-why-choose-us', 3, NULL, NULL, 'Market Expertise:', NULL, 'With a deep understanding of the real estate market, we provide insights to help you make confident decisions.', NULL, 1),
  ('realtor', 'realtor-why-choose-us', 4, NULL, NULL, 'End-to-End Support:', NULL, 'From property search to closing the deal, we are with you every step of the way.', NULL, 1),
  ('property-management', 'pm-hero', 1, NULL, NULL, 'Property Management', NULL, 'At House Bank Real Estate, we specialize in delivering end-to-end property management solutions tailored to meet your unique needs. Whether you''re a homeowner, investor, or landlord, our team ensures your property is well-maintained, your tenants are satisfied, and your investment generates the best possible returns.', '{"cta_text": "Let''s Manage your property"}', 1),
  ('property-management', 'pm-services', 0, NULL, NULL, 'What We DO', NULL, NULL, '{"kind": "header", "eyebrow": "Property management we Provide"}', 1),
  ('property-management', 'pm-services', 1, NULL, NULL, 'Tenant Management', NULL, NULL, '{"bullets": ["Tenant Screening: We conduct thorough background checks to find reliable tenants.", "Lease Agreements: Drafting, negotiation, and renewal of lease contracts.", "Tenant Support: Providing 24/7 assistance for tenant queries and concerns."]}', 1),
  ('property-management', 'pm-services', 2, NULL, NULL, 'Rent Collection and Financial Management', NULL, NULL, '{"bullets": ["Automated rent collection with on-time disbursements.", "Regular financial reporting, including income, expenses, and tax documents.", "Handling late payments and implementing penalties where necessary."]}', 1),
  ('property-management', 'pm-services', 3, NULL, NULL, 'Maintenance and Repairs', NULL, NULL, '{"bullets": ["Scheduling routine property inspections.", "Coordinating maintenance and emergency repairs with trusted contractors.", "Preventative measures to preserve the property''s value and reduce costs."]}', 1),
  ('property-management', 'pm-services', 4, NULL, NULL, 'Marketing and Vacancy Minimization', NULL, NULL, '{"bullets": ["Professional property listings with high-quality images and compelling descriptions.", "Advertising across major platforms and social media to attract tenants quickly.", "Streamlined tenant placement process to minimize vacancy periods."]}', 1),
  ('property-management', 'pm-services', 5, NULL, NULL, 'Legal and Regulatory Compliance', NULL, NULL, '{"bullets": ["Ensuring adherence to local laws, safety regulations, and zoning codes.", "Assistance with eviction procedures when necessary.", "Guidance on property insurance and liability requirements."]}', 1),
  ('property-management', 'pm-why-choose-us', 0, NULL, NULL, 'What Makes Us Standout from others', NULL, NULL, '{"kind": "header", "eyebrow": "Why Choose us"}', 1),
  ('property-management', 'pm-why-choose-us', 1, NULL, NULL, 'Expert Management Team:', NULL, 'Years of experience managing residential and commercial properties.', NULL, 1),
  ('property-management', 'pm-why-choose-us', 2, NULL, NULL, 'Tailored Solutions:', NULL, 'Customized services to suit your property type and goals.', NULL, 1),
  ('property-management', 'pm-why-choose-us', 3, NULL, NULL, 'Technology-Driven:', NULL, 'Streamlined processes using modern tools for better efficiency.', NULL, 1),
  ('property-management', 'pm-why-choose-us', 4, NULL, NULL, 'Proactive Approach:', NULL, 'Addressing potential issues before they become problems.', NULL, 1),
  ('property-management', 'pm-why-choose-us', 5, NULL, NULL, 'Client-Centric Service:', NULL, 'Clear communication and dedicated support at every step.', NULL, 1),
  ('property-management', 'pm-property-types', 0, NULL, NULL, 'Types of Properties We Manage', NULL, NULL, '{"kind": "header"}', 1),
  ('property-management', 'pm-property-types', 1, 'Home', NULL, 'Single-Family Homes', NULL, NULL, NULL, 1),
  ('property-management', 'pm-property-types', 2, 'Home', NULL, 'Apartments and Condos', NULL, NULL, NULL, 1),
  ('property-management', 'pm-property-types', 3, 'Home', NULL, 'Commercial Spaces', NULL, NULL, NULL, 1),
  ('property-management', 'pm-property-types', 4, 'Home', NULL, 'Multi-Unit Complexes', NULL, NULL, NULL, 1),
  ('home', 'home-property-guide', 1, NULL, NULL, 'Discover the easiest way to get a new property in Nigeria', NULL, NULL, NULL, 1),
  ('home', 'home-property-guide', 2, NULL, NULL, 'Our streamlined property acquisition process', NULL, NULL, NULL, 1),
  ('home', 'home-property-guide-faq', 1, NULL, NULL, 'What documents do I need to rent a property?', NULL, 'Typically, you''ll need ID proof, income proof, and references. Requirements may vary by landlord. We Typically, you''ll need ID proof, income proof, and references. Requirements may vary by landlord. Typically, you''ll need ID proof, income proof, and references. Requirements may vary by landlord. Typically, you''ll need ID proof, income proof, and references. Requirements may vary by landlord.', NULL, 1),
  ('home', 'home-property-guide-faq', 2, NULL, NULL, 'How do I know if a property is right for me?', NULL, 'Consider location, budget, amenities, and your long-term needs. Our realtors can help you evaluate properties based on your specific requirements.', NULL, 1),
  ('home', 'home-property-guide-faq', 3, NULL, NULL, 'What''s the typical rental process timeline?', NULL, 'From search to move-in usually takes 2-4 weeks, depending on availability and paperwork processing times.', NULL, 1),
  ('home', 'home-property-guide-faq', 4, NULL, NULL, 'Are utilities included in the rent?', NULL, 'This varies by property. Some include basic utilities while others don''t. Always check the lease agreement carefully.', NULL, 1),
  ('home', 'home-property-guide-faq', 5, NULL, NULL, 'How does HouseBank ensure property quality?', NULL, 'We personally vet all listings and maintain strict quality standards. Our team conducts regular property inspections.', NULL, 1),
  ('explore', 'explore-inspiration', 0, NULL, NULL, 'Get inspiration for your next properties', NULL, NULL, '{"kind": "header"}', 1),
  ('explore', 'explore-inspiration', 1, NULL, NULL, '5 of the best properties in Nigeria', NULL, 'From Abuja to every part of Nigeria, see the best recommended properties in Nigeria and the values, how it can help your portfolio positively.', '{"size": "large"}', 1),
  ('explore', 'explore-inspiration', 2, NULL, NULL, 'The 10 best real estates in Nigeria', NULL, 'A beautiful house that resonates the beauty of lagos, affordable and friendly environment', '{"size": "small"}', 1),
  ('explore', 'explore-inspiration', 3, NULL, NULL, 'The 5 best Neighbourhood in Nigeria', NULL, 'A beautiful house that resonates the beauty of lagos, affordable and friendly environment', '{"size": "small"}', 1);
